Kong/swrv

- .github/workflows/main.yml
- package.json
- src/use-swrv.ts
- tests/compile-with-webpack.js
- tests/fixtures/app.js
- tests/ssr.spec.ts
- tests/utils/compile-with-webpack.js
- yarn.lock
* supports vue native ssr and specific nuxt context
Credit goes to @Atinux for this one as he provided the code and helped iterate with me. Thank you!
Sadly, the test did not work as expected, since window is currently always defined when calling renderToString... 🤔
> feat(ssr) add ssr support

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
`mutate` was only warming the `DATA_CACHE` and was not triggering revalidations on all `swrv` instances, so a user could not easily inject data via some async event outside of the context of a `useSWRV` hook e.g. via websocket event. This adds all the `stateRef`s into a cache (essentially a `Map` wrapper) that allows mutate to access the vue reactivity when setting data/error/etc. Since each item in `REF_CACHE` is `reactive`, setting their values will trigger rerenders in each `useSWRV` instance.
This introduces a small change to existing functionality that if the `fetcherFn` is a simple function that resolves immediately e.g. `() => 'hello'`, then the `data` ref will never be undefined, but will be `hello` on first render.
Fixes #16
> feat(revalidation) add revalidation in mutate

- package.json
- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> fix(refs): only update refs of current key

- package.json
- tests/use-swrv.spec.tsx
- yarn.lock
> chore(*) bump vue composition-api peer dep

- src/types.ts
- src/use-swrv.ts
* fixes issues with hydration re: PR #31
* add server ttl config
* add default ttl of 5min
Fixes #30, #34
cc: @axelhzf
> fix(*) ttl, hydration

- README.md
- src/types.ts
- src/use-swrv.ts
> fix(error) deprecate onError

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> fix(fetcher) allow optional fetcher to not revalidate

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
- move the if statement down some lines so cache can be served across components as initially intended.
> fix(cache) serve from cache across components

- src/lib/cache.ts
- src/use-swrv.ts
- tests/use-swrv.spec.tsx
* automatic garbage collection of refs
* fixes issue  #51 with low ttl causing infinite isValidating
* ascii art
Fixes #51
> feat(cache) timer ttl eviction

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> fix(listeners) remove recursive call bug

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> fix(revalidation) dont fire if key is falsy

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
Fixes #76 for v2. Will release for v3 beta once merged.
> fix(dedupe) dedupe even when promise is resolved

- README.md
Fix a wrong code snippet in README.md.
here is a reproduction of this example snippet:
https://codesandbox.io/s/vue-3-start-forked-0t36h?file=/src/App.vue
> fix: wrong usage of Dependent Fetching

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
Fixes issue where request would be deduped, but the ref would not reset isValidating. Adds more tests.
> fix(isValidating) reset during dedupe

- src/lib/cache.ts
- src/lib/hash.ts
- src/types.ts
- src/use-swrv.ts
- tests/use-swrv.spec.tsx
* adds serialize/hash for cache
* parity with swr api
Fixes #55
> feat(args) add array/object as key

- src/types.ts
- src/use-swrv.ts
- tests/use-swrv.spec.tsx
- mutate should be immune to deduping interval
- fix mutate type
Fixes #87
> feat(mutate) force revalidate on mutate

- src/types.ts
> fix(types) data/error always defined

- .eslintrc.js
- jest.config.js
- package.json
- src/lib/is-document-visible.ts
- src/lib/is-online.ts
- src/lib/web-preset.ts
- src/types.ts
- src/use-swrv.ts
- tests/setupJest.ts
- tests/test-compat-all.sh
- tests/use-swrv.spec.tsx
- yarn.lock
Add default fetcher and move helpers to webPreset.
See issues for background:
https://github.com/vercel/swr/pull/367
https://github.com/vercel/swr/pull/690
> feat(config) add default fetcher, webPresets

- package.json
- src/use-swrv.ts
- tests/test-compat-all.sh
- yarn.lock
From https://github.com/vuejs/composition-api/pull/520
> fix(compat) use .proxy for newest composition-api

- jest.config.js
- package.json
- tests/setupJest.ts
- tests/use-swrv.spec.tsx
- yarn.lock
use `global['fetch']` to simplify things
> refactor(jest) remove whatwg-fetch dep

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> fix(timers) should refreshInterval on dependent watchers

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
even when document is not visible
Fixes #128
> fix(*) fetches data on first render

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
> chore(swrv) improved error message for top level

- README.md
Added an example of how to use SWRV with the Composition API in Vue 3
Closes #145
> Add vuex example

- README.md
- docs/configuration.md
- src/types.ts
> Pass a reactive reference as a key

- src/use-swrv.ts
- tests/use-swrv.spec.tsx
As per https://github.com/Kong/swrv/issues/262
> feat(args) add read-only computed as key (#262)

- docs/.vitepress/cache/deps/_metadata.json
- docs/.vitepress/cache/deps/package.json
- docs/.vitepress/cache/deps/vue.js
- docs/.vitepress/config.ts
- package.json
- yarn.lock
Add Algolia doc search and update dependencies
> docs(search): add algolia search

- src/use-swrv.ts
Catch an error when trying to store the data to the cache provider
> fix(cache): capture error if exception is thrown when storing data

- .github/workflows/main.yml
> ci: pin action versions
