Kong/swrv

package.json, src/use-swrv.ts
Tested v0.1.0-12-v0.1.0-15 but they should be deprecated since they were more for testing so `-16` will be next stable candidate
=> fix(ssr) assign attributes correctly

README.md
To prevent this warning: "the template root requires exactly one element".
=> Prevent a warning in the example in the README

src/use-swrv.ts
Fixes #38 and also since swrvKey on the nuxt side could be indexed at 0, so need to make sure we're checking undefined/null, since `0` would fail the conditional.
=> fix(ssr) use key as fn

src/use-swrv.ts, tests/use-swrv.spec.tsx
This PR is supposed to fix issue #88. I think we should always update the error after fetching, let me know if you think differently.
=> (fix) #88 always update error on revalidation

src/types.ts, src/use-swrv.ts, tests/use-swrv.spec.tsx
Went with the easiest exponential backoff implementation so it's easier to test / reason about: increasing the retry based on the current retry count * retry interval
example timeline:
```
dedupingInterval: 0,
errorRetryInterval: 5000,
errorRetryCount: 3
useSwrv('user', fetch) // fails
wait 5000
fetch() ... fails
wait 10000
fetch() ... fails
wait 15000
fetch() ... fails
wait 20000
max reached, don't fetch
```
Fixes #53
=> feat(error) add fetch retries on error

package.json, tests/test-compat-all.sh, tests/use-swrv.spec.tsx, yarn.lock
Adds `@vue/composition-api: "~1.0.0-beta.17"` to the compat test suite.
Related: #74
=> test(compat) add 1.x compat

src/lib/cache.ts, tests/use-swrv.spec.tsx, tsconfig.json
Can't resolve path alias because tsconfig.json is not included in npm.
Removed tsconfig.paths because it makes a mistake to use it in src.
=> fix(tsconfig): cannot resolve paths

src/cache/adapters/localStorage.ts, tests/cache.spec.tsx
Fixes `TypeError: Cannot read property 'expiresAt' of undefined` and removes encoding so that localStorage can include utf string.
=> fix(cache/localStorage) remove encoding, fix TypeError

package.json, src/types.ts, tests/test-compat-all.sh, yarn.lock
Allow for `undefined`. Also add latest rc to testing and bump allowed peerDep
Fixes #150
=> fix(types) add `undefined` to list

examples/vite/package.json, examples/vite/vite.config.js, examples/vite/yarn.lock
Updated the vite example 
* use vite 2.x stable version
* use vue 3.x stable
* configure vite and install vue plugin as needed by vite 2
=> chore: update vite example

README.md, docs/features.md
In example:
```js
const { data: projects } = useSWRV(() => user.value.id && '/api/projects?uid=' + user.value.id, fetch)
```
Accessing `user.value.id` would probably fail because `user.value` might be `undefined`...? We could also make this `user.value?.id` but I went with shorter code 😎 👇 
```js
const { data: projects } = useSWRV(() => user.value && '/api/projects?uid=' + user.value.id, fetch)
```
=> docs(example): fix "Dependent Fetching" code example

src/types.ts
Following the docs this is now allowed in typescript since the IKey cannot be a function that returns `undefined`.
```javascript
const { data: user } = useSWRV("/api/user", fetch);
const { data: projects } = useSWRV( () => user.value.id && "/api/projects?uid=" + user.value.id, fetch);
```
Here is the typescript error:
`Argument of type '() => string | undefined' is not assignable to parameter of type 'IKey'.`
The work around would be to do something like this:
```javascript
const { data: user } = useSWRV("/api/user", fetch);
const { data: projects } = useSWRV( () => (user.value.id && "/api/projects?uid=" + user.value.id)  || null, fetch);
```
=> Add undefined to IKey type

src/use-swrv.ts, tests/use-swrv.spec.tsx
When a swrv key changes, if the key value resolves to a falsey value, then set the `isValidating` accordingly, since a falsey key is never validating.
Fixes #195
=> fix(isValidating): add nullish check when no key

README.md
Change the incorrect return value name `revalidate` to `mutate`
=> docs(readme) fix incorrect `revalidate`

src/use-swrv.ts
Update the typings to allow `null` as the fetcher function
=> Allow `null` as the fetcher function

package.json
Sourcemaps point to `src` which is not distributed.
```
Sourcemap for "/node_modules/swrv/esm/cache/adapters/localStorage.js" points to missing source files
Sourcemap for "/node_modules/swrv/esm/cache/index.js" points to missing source files
Sourcemap for "/node_modules/swrv/esm/index.js" points to missing source files
Sourcemap for "/node_modules/swrv/esm/lib/hash.js" points to missing source files
Sourcemap for "/node_modules/swrv/esm/use-swrv.js" points to missing source files
Sourcemap for "/node_modules/swrv/esm/lib/web-preset.js" points to missing source files
```
=> distribute src for sourcemaps work

src/use-swrv.ts, tests/use-swrv.spec.tsx
Eliminate a (slight) memory leak caused by the indefinite retention of `StateRef`s by the `REF_CACHE` when the time-to-live is `0` by removing a `StateRef` from the `REF_CACHE` when its component is unmounted (reported in #230).
1. Checkout the source branch at commit 856002c
2. `yarn`
3. `yarn test`
4. Observe the test failures.
5. Checkout the source branch at commit 2b4a1bc
6. `yarn test`
7. Verify the tests succeed.
EDIT: Corrected commit order.
=> Remove staterefs from ref cache on unmount

tests/use-swrv.spec.tsx
Ticks differ between node versions, bump it...
=> test(*): bump ticks

src/use-swrv.ts
The following is sample code using `vue@2.6.14` and `@vue/composition-api@1.4.5`:
```vue
<template>
<div>{{ data }}</div>
</template>
<script lang="ts">
import { defineComponent } from '@vue/composition-api';
import useSWRV from 'swrv';
const fetcher = () => {
console.count('fetcher');
return Promise.reject(new Error('rejected!'));
};
export default defineComponent({
name: 'App',
setup() {
const { data } = useSWRV('/api/v2/foo', fetcher, {
errorRetryCount: 0,
});
return {
data,
};
},
});
</script>
```
When you run the code above, you'll see the following in your browser's console:
```
fetcher: 1
fetcher: 2
fetcher: 3
fetcher: 4
fetcher: 5
fetcher: 6
fetcher: 7
fetcher: 8
fetcher: 9
fetcher: 10
fetcher: 11
fetcher: 12
fetcher: 13
fetcher: 14
fetcher: 15
fetcher: 16
fetcher: 17
fetcher: 18 …
```
=> fix(errorRetryCount): Make sure fetcher doesn't run endlessly when errorRetryCount is set to 0

src/use-swrv.ts
Prevent retrying on error if the component has been unmounted. Resolves #218.
=> fix(unmounted): prevent retry if component is unmounted

src/use-swrv.ts
Removing unneeded await from setTimeout call. Resolves #323.
=> fix(use-swrv): do not await set timeout to execute

.github/workflows/main.yml
Adds `timeout-minutes` to CI jobs to prevent jobs from running too long
=> feat(ci): add timeout-minutes to ci jobs [KHCP-8104]
